name: IMGW raport

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # codziennie 08:00 czasu PL

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib
          playwright install chromium

      # ✅ tworzy credentials.json z GitHub Secret
      - name: Create credentials file
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

      - name: Run script
        run: python script.py

      - name: Upload backup (opcjonalne)
        uses: actions/upload-artifact@v4
        with:
          name: raport
          path: '*.csv'
